DROP SCHEMA IF EXISTS アカウント CASCADE;
CREATE SCHEMA アカウント;

CREATE TABLE アカウント.ユーザー
(
    ユーザーID SERIAL PRIMARY KEY,
    ログイン名 VARCHAR(256) UNIQUE ,
    パスワード VARCHAR(256)
);

CREATE TABLE アカウント.ユーザー役割
(
    ユーザーID INT ,
    役割 VARCHAR(256),
    FOREIGN KEY (ユーザーID) REFERENCES アカウント.ユーザー(ユーザーID)
);


-- CREATE TABLE USERS
-- (
--     USERNAME VARCHAR(50) NOT NULL,
--     PASSWORD VARCHAR(68) NOT NULL,
--     ENABLED BOOLEAN NOT NULL,
--     PRIMARY KEY(USERNAME)
-- );
--
--
-- CREATE TABLE AUTHORITIES
-- (
--     USERNAME VARCHAR(50) NOT NULL,
--     AUTHORITY VARCHAR(68) NOT NULL,
--     FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
-- );

CREATE SCHEMA ワークフロー;
CREATE TABLE ワークフロー.申請書
(
    申請ID UUID NOT NULL,
    金額 NUMERIC(7) NOT NULL,
    用途 TEXT NOT NULL,
    PRIMARY KEY (申請ID),
    作成日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ワークフロー.ワークフロー履歴
(
    申請ID UUID NOT NULL,
    ワークフロー履歴ID UUID NOT NULL,
    イベント VARCHAR(3) NOT NULL,
    PRIMARY KEY (申請ID, ワークフロー履歴ID),
    FOREIGN KEY (申請ID) REFERENCES ワークフロー.申請書 (申請ID),
    作成日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ワークフロー.申請
(
    申請ID UUID NOT NULL,
    申請者ID BIGINT NOT NULL,
    申請日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (申請ID),
    FOREIGN KEY (申請ID) REFERENCES ワークフロー.申請書 (申請ID),
    FOREIGN KEY (申請者ID) REFERENCES アカウント.ユーザー(ユーザーID),
    作成日時 TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ワークフロー.最新履歴
(
    申請ID UUID NOT NULL,
    ワークフロー履歴ID UUID NOT NULL,
    ステータス VARCHAR(3) NOT NULL,
    PRIMARY KEY (申請ID),
    FOREIGN KEY (申請ID, ワークフロー履歴ID) REFERENCES ワークフロー.ワークフロー履歴(申請ID, ワークフロー履歴ID),
    作成日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ワークフロー.担当履歴
(
    申請ID UUID NOT NULL,
    ワークフロー履歴ID UUID NOT NULL,
    ユーザーID BIGINT NOT NULL,
    PRIMARY KEY (申請ID, ワークフロー履歴ID),
    FOREIGN KEY (申請ID, ワークフロー履歴ID) REFERENCES ワークフロー.ワークフロー履歴(申請ID, ワークフロー履歴ID),
    FOREIGN KEY (ユーザーID) REFERENCES アカウント.ユーザー(ユーザーID),
    作成日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);