DROP SCHEMA IF EXISTS アカウント CASCADE;
CREATE SCHEMA アカウント;

CREATE TABLE アカウント.ユーザー
(
    ユーザーID SERIAL PRIMARY KEY,
    ログイン名 VARCHAR(256) UNIQUE ,
    パスワード VARCHAR(256)
);

CREATE TABLE アカウント.ユーザー役割
(
    ユーザーID INT ,
    役割 VARCHAR(256),
    FOREIGN KEY (ユーザーID) REFERENCES アカウント.ユーザー(ユーザーID)
);


CREATE TABLE USERS
(
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(68) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    PRIMARY KEY(USERNAME)
);


CREATE TABLE AUTHORITIES
(
    USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(68) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);