mybatis:
  config-location: classpath:mybatis.xml

spring:
  application:
    name: work-flow
  jackson:
    visibility:
      field: non_private
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: ALWAYS
      encoding: utf-8
      schema-locations:
        - classpath:schema.sql
      data-locations:
        - classpath:data.sql
  thymeleaf:
    cache: false
    prefix: file:app/workflow/src/main/resources/templates/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: info
    workflow:
      infrastructure.datasource: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'