version: '3'
services:
  rabbit:
    image: rabbitmq:3.9-management-alpine
    hostname: workflow-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"